global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 5s # Evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: 'metrics_service'
  static_configs:
    - targets: ['go-metrics-api:8001']
